[package]
name = "learning_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = '0.4.0'
futures = "0.3"
tokio = "1.0"
mini-redis = "0.4"
bytes = "1"

